---
collections:
- name: amazon.aws
- name: servicenow.itsm
- name: awx.awx
- name: redhat.rhel_system_roles
- name: redhat.insights
- name: community.crypto
- name: community.aws
- name: community.general